version: "3.8"
services:
  backend:
    build: ./backend
    container_name: urlshort_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
  frontend:
    build: ./my-frontend
    container_name: urlshort_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
